### ISSUE TITLE
How do you invoke :VBox?

### ISSUE THREAD

**Issue by dvanderweele** [jbyuki/venn.nvim#1]
I am curious how you are "invoking :VBox" after making your selection, I can't quite figure it out. On the bottom right of your gif it shows <20> every time you "invoke". What does that mean?

Thanks, I realize it probably isn't an issue with your library, but with me being somewhat of a newb with neovim. Great tool tho! I'd love to use it.

**Comment by jbyuki** [comment]
If I remember correctly it's done using the following keymap:
`vnoremap <leader>g :VBox<CR>` where my leader key is set to space hence the <20> (see `:h mapleader` if you need clarifications on that).

Does it answer your question? I'm happy to help.

**Comment by dvanderweele** [comment]
Wow, thanks for the speedy response! 

Well these are the two relevant lines of my mom config:

```
let mapleader = ','
vnoremap <Leader>g :VBox<CR>
```

I also tried `xnoremap` and `noremap` to no avail. Along with a space as you use, and that didn't work either. Any ideas?

**Comment by jbyuki** [comment]
Putting the two lines in your config is correct. It might be the `<leader>` which needs to be in lowercase. Can you see if it solves it?

**Comment by dvanderweele** [comment]
LoL that worked. Thank you so much for your help 🤙
