### ISSUE TITLE
UTF 8 error when drawing line with arrow

### ISSUE THREAD

**Issue by zdcthomas** [jbyuki/venn.nvim#11]
Hello! 
First off, I absolutely love the plugin, thank you so much for making it. 
When I try to draw a line with an arrow terminating in all directions in any filtetype, I see this error.

<img width="1680" alt="Screen Shot 2021-10-29 at 12 57 47 PM" src="https://user-images.githubusercontent.com/36716240/139488058-7e40be0e-b632-4a27-8533-9cda2b4962ca.png">

I've tried pasting the   ▲  ◄─┼─►▼ characters directly, but that does not cause the same issue.

**Comment by jbyuki** [comment]
Hi,

What happens if you deactivate LSP in the buffer?

**Comment by zdcthomas** [comment]
I no longer get the error. Which makes sense because it seems like the issue is that the characters are getting sent over the rpc I guess? 
I could add an LspStop to the venn toggle function for now

**Comment by jbyuki** [comment]
I guess so. It seems to be an issue with the built-in client not handling special UTF characters. I'll close this for now.
