### ISSUE TITLE
Newbie issues with configuring

### ISSUE THREAD

**Issue by moondialectix** [jbyuki/venn.nvim#15]
Hey, sorry for the issue, can't invoke VBox and when I start up nvim I get these error messages from the config file

Error detected while processing /home/moondialectix/.config/nvim/init.vim:
line    8:
E492: Not an editor command: -- venn.nvim: enable or disable keymappings
line    9:
E121: Undefined variable: _G
line   10:
E492: Not an editor command:     local venn_enabled = vim.inspect(vim.b.venn_ena
bled)
line   11:
E121: Undefined variable: venn_enabled
E15: Invalid expression: venn_enabled == "nil" then
line   26:
E580: :endif without :if: end
line   27:
E492: Not an editor command: -- toggle keymappings for venn using <leader>v
"nvim_set_keymap('n'," [New File]
Cannot open file "nvim_set_keymap('n',"
"'<leader>v'," [New File]
"":lua" [New File]             
"Toggle_venn()<CR>"," [New File]
"{" [New File]                        
Cannot open file "{"
"noremap" [New File]
Cannot open file "noremap"
"=" [New File]
Cannot open file "="
"true})" [New File]
Cannot open file "true})"
line   28:
E480: No match: api

**Comment by jbyuki** [comment]
Hi,

It seems the errors are showing because init.vim is Vimscript but the configuration is in Lua.
Try putting the configuration code inside delimiters like this:
```
lua << END
  ...
END
```

I hope this solves the issues.

**Comment by moondialectix** [comment]
thank you so much! That solved the errors, but I still can't invoke VBox. I saw the other issue that was resolved, my question is: where should I put:

vnoremap <leader>g :VBox<CR>

relative to the rest of the text copied from the readme

**Comment by jbyuki** [comment]
If you've just copy-pasted the config from the README, you should be able to invoke VBox using the key `f`.
I'll repeat the usage steps just for convenience:
1. `:set ve=all` to freely move the cursor.
2. Select a box using `<C-V>` or `Ctrl + V`, then move the cursor to make a box
3. Press `f`, this should draw the box.

You can always change the keybindings to your liking, by modying the `nvim_buf_set_keymap` call arguments.

**Comment by moondialectix** [comment]
this works! thanks man, sorry for the bother

**Comment by jbyuki** [comment]
Sorry, I wasn't really clear on my last instructions, but if it works, great!
