### ISSUE TITLE
Issues when installing using Plug

### ISSUE THREAD

**Issue by opensourcegeek** [jbyuki/venn.nvim#16]
I've just tried to install this plugin using `Plug` and I get the following error,
```
x venn.nvim:
    fatal: invalid reference: master
```

I thought it's probably pointing to master when the branch is called 'main'. So I installed this plugin using `Plug 'jbyuki/venn.nvim', { 'branch': 'main' }` and that worked without errors. But now when I invoke `:VBox` I get 'Not an editor command :VBox'. I tried `PlugClean` just to make sure nothing was getting left behind when it errors out, but still the same issue. I haven't added your key mappings by the way, but I think the `:VBox` command should work regardless, isn't it? Thanks for what looks like a really promising drawing plugin for nvim. (Been using mermaidjs in markdown files, but this will mean I can draw in any file - cheers for that)

**Comment by jbyuki** [comment]
Hi there,
This might just be that venn.nvim was not installed for some reason. Yes, if the plugin is installed `:VBox` is automatically enabled. You could try to check if venn is present in `:echo stdpath('data')`. If not, you might have to install it once again.

**Comment by opensourcegeek** [comment]
Thanks @jbyuki - it's not there but when I `PlugInstall` again it says it's already installed (`- venn.nvim: Already installed
`).  I do see it in `plugged` dir though (`~/.config/nvim/plugged/venn.nvim/`).

**Comment by jbyuki** [comment]
Let's try something, if you type `:scriptnames`, do you see `../plugged/venn.nvim/plugin/venn.vim` being sourced? If the file is there it should be.

**Comment by opensourcegeek** [comment]
Sorry for the delayed response, as I was off for couple of days. I'm on neovim (v0.6.1), I was on an older version earlier - 0.5.x. So, I tried updating neovim and installing the plugin again. It works fine now, I don't think I changed anything other than neovim version. Thanks for looking into this, happy it's working now :)
