### ISSUE TITLE
Initialization function from README fails

### ISSUE THREAD

**Issue by matu3ba** [jbyuki/venn.nvim#17]
Running inside cmd window with `:lua Toggle_venn` fails with
```txt
E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'
```

Subsequent drawing is then not possible with `HJKL`.

Running `:VBox<CR>` still works though.

**Comment by jbyuki** [comment]
The paranthesis in the call is missing. So the correct call would be `:lua Toggle_venn()`.

There are some cases where you can omit the parenthesis in Lua such as with a single string argument or table argument but with no argument, it throws a an error.

**Comment by matu3ba** [comment]
Thanks.

I should have added the exact circumstances, because I cant reproduce now.
Closing.
