### ISSUE TITLE
Suggestion: add command for double line box characters

### ISSUE THREAD

**Issue by AckslD** [jbyuki/venn.nvim#2]
Great plugin :tada: 

Maybe there could be another command, eg `:VBoxDouble` which uses `═`, `║` etc? Could also be one for thicker ones

**Comment by jbyuki** [comment]
Thanks!
It could be nice a addition to expand the tool. I will consider it.

**Comment by jbyuki** [comment]
Please check out the last commits I added `:VBoxD` and `:VBoxB` for double and thick. I will also add support for crossing shortly.

**Comment by AckslD** [comment]
Awesome, works great! :tada:
