### ISSUE TITLE
Allow modification of arrow icons

### ISSUE THREAD

**Issue by siduck** [jbyuki/venn.nvim#21]
Hi there, the right arrow icon looks bad here 

![image](https://user-images.githubusercontent.com/59060246/185462345-4ec96660-1e43-44a3-8b65-3e83c87c8bf4.png)

it would be great if we could customize it!

I would use this icon 

![image](https://user-images.githubusercontent.com/59060246/185462472-d199bef4-1f94-4658-9ea1-42ca9bc80d9b.png)

![image](https://user-images.githubusercontent.com/59060246/185462516-5916ebab-e838-48ad-9b0d-257334ce3d89.png)

or this 

![image](https://user-images.githubusercontent.com/59060246/185462579-241042ac-1b13-4d8b-a150-c1860a9f31d7.png)

**Comment by jbyuki** [comment]
It should already be possible to customize it to your liking. See [here](https://github.com/jbyuki/venn.nvim/issues/13#issuecomment-1107845218).

**Comment by siduck** [comment]
thanks a lot!
