### ISSUE TITLE
How to work around so that I can use it in vim (not neovim)

### ISSUE THREAD

**Issue by lixueyi83** [jbyuki/venn.nvim#24]
I tried to include this into vim (other than neovim), it does not work. Is it doable or any work around that allow me to use this plug in vim? Thank you very much!

**Comment by jbyuki** [comment]
Support for vim is not considered at the moment. As the plugin is written in .lua, it would require a complete rewrite. I suggest looking into alternatives for vim.

* [Drawit](https://github.com/vim-scripts/DrawIt) (or one interesting [fork](https://github.com/joshzcold/DrawIt) )
* [vim-boxdraw](https://github.com/gyim/vim-boxdraw)
