### ISSUE TITLE
Support crossings

### ISSUE THREAD

**Issue by AckslD** [jbyuki/venn.nvim#3]
Currently if you draw a line over another it replaces any existing characters such as:
```
                   ▲
                   │
     ┌──────┐  │   │
     │      ├──│───┘
     └──────┘  │
               ▼

```
which in some cases might be desirable but it would also be great to get the crossing characters such as `┼`.

If #2 is implemented there might be more crossings to consider.

**Comment by jbyuki** [comment]
This is already possible in 2 steps.
```
  │
  ▼
─────►
```

Elongate the upper arrow to the horizontal arrow.
```
  │
  │
──┴──►
```

Elongate from the crossing.
```
  │
  │
──┼──►
  ▼
```

Does that help? I would be happy to discuss it.
Like you said, sometimes `┼` or `─│─` is desirable which the current implementation allows you to do both.

**Comment by AckslD** [comment]
Yes, awesome! Thanks for the help!

**Comment by AckslD** [comment]
@jbyuki Is it also possible to do this on some nice ways for boxes also?

For example if I want to draw the following:
```
┌┬┐
└┴┘
```

**Comment by jbyuki** [comment]
I would also do it in 2 steps:
```
┌─┐
└─┘
```
Draw the outline of the box.
```
┌┬┐
└┴┘
```
Draw a line vertically which cuts the box in half. The arrow disappears because the end is automatically merged. The character which is at the end of the line and the direction of the line determines the merged glyph.

Horizontally it's also possible of course:
```
┌┐
├┤
└┘
```

How is that for a nice way?

**Comment by AckslD** [comment]
Thanks for your reply @jbyuki! Maybe the example was not the best but I sometimes notice that I want to have crossings between boxes, without having to draw all of the sides of the boxes manually. A better example is probably:

What I get:
```
     ┌────┐
  ┌──│──┐ │
  │  └────┘
  │     │
  └─────┘
```
What I want:
```
     ┌────┐
  ┌──┼──┐ │
  │  └──┼─┘
  │     │
  └─────┘
```

**Comment by jbyuki** [comment]
Let's see how well it's working!

Crossings variation of commands can be invoked with `VBoxO`, `VBoxDO`,  `VBoxHO`.

**Comment by jbyuki** [comment]
It also supports crossings between line types (double, heavy) but double - heavy is not in the (unicode box drawing character set) [https://en.wikipedia.org/wiki/Box-drawing_character] so this is the only exception which doesn't work.

**Comment by AckslD** [comment]
Works great @jbyuki :+1
