### ISSUE TITLE
[BUG] venn.nvim crashes my neovim

### ISSUE THREAD

**Issue by qvieth** [jbyuki/venn.nvim#5]
https://user-images.githubusercontent.com/71810726/126884409-d09958b8-496c-4c4e-8751-837ea91822c3.mp4

using venn.nvim stop my nvim from working

**Comment by jbyuki** [comment]
This seems to be venn.vnim updated to the latest commit but I cannot reproduce on my setup.

Maybe try updating venn again, I added logging.
Try to make it crash and send me the log available under `nvim-data/venn.log` ( the `nvim-data` can be located using `:echo stdpath('data')` ). This will narrow down the debugging.

**Comment by jbyuki** [comment]
And logging must be enabled with `:let g:venn_debug = v:true`.

**Comment by qvieth** [comment]
thank you @jbyuki !, here's the log files.

[venn.log](https://github.com/jbyuki/venn.nvim/files/6873647/venn.log)

**Comment by jbyuki** [comment]
thanks that was helpful. Interesting bug.
Probably a keymapping is set on `vv` which make it go into an infinite loop but not completely sure.

Could you try again and send me the log?

**Comment by qvieth** [comment]
@jbyuki Updated and it works again!! Thank you so much for your works on this incredible plugin!!

[venn.log](https://github.com/jbyuki/venn.nvim/files/6873888/venn.log)
