### ISSUE TITLE
Easy to make T shape and also a cross using this Unicode '┼', '╬' and '╋;

### ISSUE THREAD

**Issue by anurag3301** [jbyuki/venn.nvim#7]
### It would be very easy to make T shapes like this

https://user-images.githubusercontent.com/52702259/128589697-0c070c1d-91c9-4573-87a0-d85234086d0a.mp4

### And please add this character '┼', '╬' and '╋  with cross shape integration.

https://user-images.githubusercontent.com/52702259/128589718-d32b5195-8a5f-48db-a315-d75b6d8f17c5.mp4

**Comment by jbyuki** [comment]
Please try `:VBoxO`. It should do what you are looking for.

`VBoxDO` and `VBoxHO` are variations for double and heavy respectively.
